language: node_js
node_js: "6"
addons:
  apt:
    packages:
    - g++-4.8
    - gcc-4.8
    - xvfb
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip -O /tmp/chromedriver
  - chmod 777 /tmp/chromedriver
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - BROWSERS=chrome npm test
env:
  - CHROME_DRIVER_PATH=/tmp/chromedriver
